version: '3.8'
services:
  bot:
    image: ${IMAGE_REPO:-aredl-manager-v3:local}
    configs:
      - source: bot_config
        target: /app/config.json
    volumes:
      - type: bind
        source: ${DEPLOY_PATH}/data
        target: /app/data
    environment:
      - NODE_ENV=production
    secrets:
      - aredl_manager_v3_bot_token
      - aredl_manager_v3_api_token
configs:
  bot_config:
    file: ./config.template.json
    template_driver: golang

secrets:
  aredl_manager_v3_bot_token:
    external: true
  aredl_manager_v3_api_token:
    external: true